### PR TITLE
Sections 1 and 2 edits

### PR DESCRIPTION
**Pull request by jgabry**
Fixes some typos and does some very minor content rearrangement.

### CODE REVIEW

**Comment by jgabry** [comment]
@betanalpha This is fantastic and very much needed. If this pull request is helpful then I'm happy to do the same for the remaining sections as I read through it.

**Comment by jgabry** [comment]
(I was referring to your document as fantastic and very much needed, not my pull request)

**Comment by betanalpha** [comment]
Can you split this up into the typos and the reorganization?
I see what you’re trying to do with the reorganization, but
it also breaks the flow the subsections and isn’t consistent
with the others.  I think there are better ways of emphasizing
the content rather than just sticking new headers in.

**Comment by jgabry** [comment]
Yeah, I'll split it up.

**Comment by betanalpha** [comment]
Actually, put the reorg details into an issue, if you could.  Thanks.

**Comment by jgabry** [comment]
sure

**Pull request closed without merging**
